### ISSUE TITLE
1.1.0 Release

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-jwpl#132]
Checklist for the next (maintenance) release.

- [x] Check for non-DKPro Snapshot dependencies
- [x] Consider upgrading to DKPro parent POM 13 (Java 8)
- [x] Check for used/unused (un)declared dependencies
- [x] Update scope of dependencies
- [x] Stage/Release
- [x] Drafting the release (https://github.com/dkpro/dkpro-jwpl/releases)
- [x] Announce release

**Comment by daxenberger** [comment]
Release staged at https://oss.sonatype.org/content/repositories/central_bundles-6916/. Please anybody check and upvote.

**Comment by reckart** [comment]
de.tudarmstadt.ukp.wikipedia.revisionmachine-1.1.0 contains a log4j.properies file. Normally libraries should not contain configuration files for logging frameworks. They are highly likely to conflict with logging configurations used by applications that build on the library. Such files should reside in src/test/resources if required for testing, not in src/main/resources.

**Comment by reckart** [comment]
de.tudarmstadt.ukp.wikipedia.revisionmachine-1.1.0 contains a configSamples folder - probably shouldn't be in there.

**Comment by daxenberger** [comment]
> de.tudarmstadt.ukp.wikipedia.revisionmachine-1.1.0 contains a configSamples folder - probably shouldn't be in there.

What is the best way to exclude such files/folders from deployment? Or, where would you locate such sample files if not in src/main/resources?

**Comment by reckart** [comment]
You can configure the maven resource plugin to leave out certain files or file patterns when copying resources to the target folder. E.g. https://maven.apache.org/plugins/maven-resources-plugin/examples/include-exclude.html

Alternatively, files that are not required at test-time or runtime probably don't have to be located in src/(main/test)/resources at all - they could e.g. be in src/xxx/examples.

**Comment by daxenberger** [comment]
I've addressed the issues above.

New staging at: https://oss.sonatype.org/content/repositories/central_bundles-6920/

**Comment by ferschke** [comment]
The logging was included after so many complaints and questions on the list
why a log4j error message was displayed when they created a JWPL or Revision
database.
To make this stream of complaints end, we just added a configuration.
That doesn¹t mean it should be in there.

Looks good. Thanks for preparing the release.
No I can finally include the Wikipedia module in the next DiscourseDB
release.  ;)

From:  Richard Eckart de Castilho <notifications@github.com>
Reply-To:  dkpro/dkpro-jwpl
<reply+00076ed910c3951572bf44ddaa60442ac10f1a8b34b106ec92cf00000001133110149
2a169ce08b91734@reply.github.com>
Date:  Thursday, April 21, 2016 at 6:03 PM
To:  dkpro/dkpro-jwpl <dkpro-jwpl@noreply.github.com>
Subject:  Re: [dkpro/dkpro-jwpl] 1.1.0 Release (#132)


de.tudarmstadt.ukp.wikipedia.revisionmachine-1.1.0 contains a
log4j.properies file. Normally libraries should not contain configuration
files for logging frameworks. They are highly likely to conflict with
logging configurations used by applications that build on the library. Such
files should reside in src/test/resources if required for testing, not in
src/main/resources.


You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/dkpro/dkpro-jwpl/issues/132#issuecomment-213130424>

**Comment by daxenberger** [comment]
I can't release the staged repo: "Nexus returned an error: ERROR 403: Forbidden". Googling points to unmatched groups ids in the pom as a reason for this. Could the namespace change in the **parent pom** (org.dkpro v.14) be the reason for this? We haven't changed the namespace of JWPL to reflect this...

**Comment by reckart** [comment]
The ID of the parent POM does not matter. Only the IDs of the stages POMs. I would suggest opening a Jira issue with Sonatype to inquire about this.

**Comment by reckart** [comment]
Artifacts' groupIDs to not have to match the groupIDs of their parent POMs.

**Comment by daxenberger** [comment]
https://issues.sonatype.org/browse/MVNCENTRAL-1062

**Comment by reckart** [comment]
The project for such issues in Jira is usually "Community Support - Open Source Project Repository Hosting (OSSRH)"

**Comment by daxenberger** [comment]
filed new issue at https://issues.sonatype.org/browse/OSSRH-22034.

**Comment by daxenberger** [comment]
Finally, released...On maven central.

**Comment by zesch** [comment]
Great 👍
Johannes Daxenberger <notifications@github.com> schrieb am Mo., 25. Apr.
2016 um 23:12:

**Comment by reckart** [comment]
Kawabunga :)

**Comment by kanecko** [comment]
Will there be a fatjar version of DataMachine available on Maven Central (de.tudarmstadt.ukp.wikipedia.datamachine-1.1.0-jar-with-dependencies.jar)?
I see all the previous versions had it, but not the current one.

**Comment by reckart** [comment]
@kanecko I was kind of objecting against having fat jars on Maven Central because using fat jars as dependencies is really a bad idea. We can offer fat jars, but I would suggest attaching as binary downloads to the respective release tags on Github: https://github.com/dkpro/dkpro-jwpl/releases/tag/de.tudarmstadt.ukp.wikipedia-1.1.0

**Comment by daxenberger** [comment]
@kanecko As @reckart  explained, we've decided against uploading them to Maven Central, but I'll make them available with the release tag (together with the release notes which are still pending...)

**Comment by kanecko** [comment]
That sounds good.

**Comment by daxenberger** [comment]
Done.

**Comment by ferschke** [comment]
👍
