### ISSUE TITLE
Switch to "org.dkpro" style

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-jwpl#165]
Switch names:

- groupId / package prefix: `org.dkpro.jwpl`
- artifactIds / module subdirectpries: `dkpro-jwpl-XXX`

**Comment by mawiesne** [comment]
Should this be part of milestone [1.2.0](https://github.com/dkpro/dkpro-jwpl/milestone/2) or shall we put it into [1.2.1](https://github.com/dkpro/dkpro-jwpl/milestone/3)? 

Feel free to assign it.

**Comment by reckart** [comment]
I think this should go into a feature-level release (middle digit increase) and not into a bug-fix release (last digit increase). So 1.2.0 or 1.3.0.

**Comment by mawiesne** [comment]
I also created [1.3.0](https://github.com/dkpro/dkpro-jwpl/milestone/5) a couple of minutes ago. 

As we want to release [1.2.0](https://github.com/dkpro/dkpro-jwpl/milestone/2) in the near future and devs have their code base bound to using 1.2.0 snapshots, I would _prefer_ a change in groupId / artifactIds with an upcoming _1.3.0_. Otherwise, this could cause some headache for other/consuming code bases.

**Comment by mawiesne** [comment]
New milestone target: 2.0.0
