### ISSUE TITLE
MyISAM instead of InnoDB

### ISSUE THREAD

**Issue by dryleaf** [dkpro/dkpro-jwpl#204]
Probably nothing, but just curious:
- Why is it that `MyISAM` in is used instead of `InnoDB`?

reference:
https://github.com/dkpro/dkpro-jwpl/blob/master/de.tudarmstadt.ukp.wikipedia.wikimachine/jwpl_tables.sql#L46

**Comment by reckart** [comment]
I believe when I asked the same thing back in the day, somebody responded to me that JWPL wouldn't need transaction management (since it is mostly read-only) and that for the particular JWPL use-case MyISAM would be more efficient. But I never verified this myself nor do I have any idea if this would still hold today. Feel free to evaluate and report back to us :)

**Comment by reckart** [comment]
No further questions, so I'll assume this one is resolved.
