### ISSUE TITLE
ModularParser getLanguages() returns null

### ISSUE THREAD

**Issue by daxenberger** [dkpro/dkpro-jwpl#82]
Originally reported on Google Code with ID 88

```
What steps will reproduce the problem?

I'm using api-0.9.1.

// body = raw text of: http://de.wikipedia.org/wiki/Americium
parser = new MediaWikiParserFactory(Language.german);
ParsedPage pp = parser.parse(body);

// This returns null, instead of more than a dozen of languages
pp.getLanguages();
```

Reported by `xiaoruoruo` on 2012-04-12 17:59:43

**Comment by mawiesne** [comment]
I reproduced this case as reported by `xiaoruoruo` on 2012 with these findings:
- The `ModularParser` can't be used to parse all details (categories, languages...) from a plain "raw text" input, as reported by her/him.
- To avoid running into a `NullPointerException` one needs to compensate the current impl of `ModularParser#getSpecialLinks(...)` so that an non-null yet empty `ContentElement` is returned. 
- However, with the workaround applied, no languages and/or categories can be found as the raw text simply has nothing to parse and match.

I will open a PR with the patch to avoid NPEs, though.
